### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/taskvine-report-tool#1]
Some aspects that can be improved for this system:

Enhancements:

- [x] Don't display the log files if they are too large, download instead on click.
- [x] Redirect to the same log on refresh.
- [x] Error handling if csv files don't exist.
- [x] Give each log entry a unique url.
- [ ] Format the multiple-item table cells, like _workers held_ in **File Summary**.
- [ ] Provide a way for users to place their logs anywhere.
- [ ] Use global pd data structures to speed up switching table pages.
- [ ] Sort by column in a search mode.
- [x] Generate data for multiple logs in one go.
- [ ] Choose a different start time.
- [ ] Use percentage progress instead of elapsed time in many vis.
- [ ] Show the total amount of disk used.

Visualizations:
- [ ] How tasks are dispatched from the manager's point of view.
- [ ] Task Concurrency on each worker
- [ ] Category Summary
- [x] Manager Disk Usage
